server:
  port: 8080
spring:
  application:
    name: example-frame
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.liuchuang.model
  global-config:
    banner: true
    db-config:
      id-type: AUTO
      logic-delete-value:  #逻辑已删除值

